# **1.** **Machine Learning Regression**

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-02-car-price/data.csv'

In [4]:
!wget $data #wget = download file from the internet

--2026-09-10 09:56:27--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/refs/heads/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: 'data.csv.1'

     0K .......... .......... .......... .......... ..........  3% 5.33M 0s
    50K .......... .......... .......... .......... ..........  6% 3.88M 0s
   100K .......... .......... .......... .......... .......... 10% 22.9M 0s
   150K .......... .......... .......... .......... .......... 13%  142M 0s
   200K .......... .......... .......... .......... .......... 17% 5.62M 0s
   250K .......... .......... .......... .......... .......... 20% 20.7M 0s
   300K .......... .......... .......... .......... .......... 24% 66.0M 0s
   350K .......... .......... .......... .......... .......... 27% 88.8M 0s
   400K .......... .......... .......... .......... .......... 31%  206M 0s
   450K .......... .......... .......... .......... .......... 34% 4.40M 0s
   500K .......... .......... .......... .......... .......... 38%  151M 0s
   550K .......... .......... .......... .......... .......... 41% 98.8M 0s
   600K .......... .......... .......... .......... .......... 45% 76.8M 0s
   650K .......... .......... .......... .......... .......... 48%  151M 0s
   700K .......... .......... .......... .......... .......... 52% 30.0M 0s
   750K .......... .......... .......... .......... .......... 55%  203M 0s
   800K .......... .......... .......... .......... .......... 58% 35.8M 0s
   850K .......... .......... .......... .......... .......... 62%  204M 0s
   900K .......... .......... .......... .......... .......... 65%  183M 0s
   950K .......... .......... .......... .......... .......... 69% 4.13M 0s
  1000K .......... .......... .......... .......... .......... 72% 59.3M 0s
  1050K .......... .......... .......... .......... .......... 76%  145M 0s
  1100K .......... .......... .......... .......... .......... 79%  184M 0s
  1150K .......... .......... .......... .......... .......... 83%  216M 0s
  1200K .......... .......... .......... .......... .......... 86% 80.9M 0s
  1250K .......... .......... .......... .......... .......... 90%  105M 0s
  1300K .......... .......... .......... .......... .......... 93%  233M 0s
  1350K .......... .......... .......... .......... .......... 97%  249M 0s
  1400K .......... .......... .......... ..........           100% 22.2M=0.07s

2026-09-10 09:56:27 (20.1 MB/s) - 'data.csv.1' saved [1475504/1475504]

http://#wget: Invalid host name.
--2026-09-10 09:56:27--  http://=/
Resolving = (=)... failed: No such host is known. .
wget: unable to resolve host address '='
--2026-09-10 09:56:27--  http://download/
Resolving download (download)... failed: No such host is known. .
wget: unable to resolve host address 'download'
--2026-09-10 09:56:30--  http://file/
Resolving file (file)... failed: No such host is known. .
wget: unable to resolve host address 'file'
--2026-09-10 09:56:32--  http://from/
Resolving from (from)... failed: No such host is known. .
wget: unable to resolve host address 'from'
--2026-09-10 09:56:35--  http://the/
Resolving the (the)... failed: No such host is known. .
wget: unable to resolve host address 'the'
--2026-09-10 09:56:38--  http://internet/
Resolving internet (internet)... failed: No such host is known. .
wget: unable to resolve host address 'internet'
FINISHED --2026-09-10 09:56:40--
Total wall clock time: 14s
Downloaded: 1 files, 1.4M in 0.07s (20.1 MB/s)

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [7]:
df.columns.str.lower()

Index(['make', 'model', 'year', 'engine fuel type', 'engine hp',
       'engine cylinders', 'transmission type', 'driven_wheels',
       'number of doors', 'market category', 'vehicle size', 'vehicle style',
       'highway mpg', 'city mpg', 'popularity', 'msrp'],
      dtype='str')

In [10]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [12]:
df.dtypes #tgk datatype

make                     str
model                    str
year                   int64
engine_fuel_type         str
engine_hp            float64
engine_cylinders     float64
transmission_type        str
driven_wheels            str
number_of_doors      float64
market_category          str
vehicle_size             str
vehicle_style            str
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

In [14]:
df.dtypes == 'str'

make                  True
model                 True
year                 False
engine_fuel_type      True
engine_hp            False
engine_cylinders     False
transmission_type     True
driven_wheels         True
number_of_doors      False
market_category       True
vehicle_size          True
vehicle_style         True
highway_mpg          False
city_mpg             False
popularity           False
msrp                 False
dtype: bool

In [15]:
df.dtypes[df.dtypes == 'str']

make                 str
model                str
engine_fuel_type     str
transmission_type    str
driven_wheels        str
market_category      str
vehicle_size         str
vehicle_style        str
dtype: object

In [16]:
df.dtypes[df.dtypes == 'str'].index

Index(['make', 'model', 'engine_fuel_type', 'transmission_type',
       'driven_wheels', 'market_category', 'vehicle_size', 'vehicle_style'],
      dtype='str')

In [18]:
list(df.dtypes[df.dtypes == 'str'].index)

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [19]:
strings = list(df.dtypes[df.dtypes == 'str'].index)
strings

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [20]:
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_') #buat untuk setiap dlm column

In [21]:
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,bmw,1_series_m,2011,premium_unleaded_(required),335.0,6.0,manual,rear_wheel_drive,2.0,"factory_tuner,luxury,high-performance",compact,coupe,26,19,3916,46135
1,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,convertible,28,19,3916,40650
2,bmw,1_series,2011,premium_unleaded_(required),300.0,6.0,manual,rear_wheel_drive,2.0,"luxury,high-performance",compact,coupe,28,20,3916,36350
3,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,"luxury,performance",compact,coupe,28,18,3916,29450
4,bmw,1_series,2011,premium_unleaded_(required),230.0,6.0,manual,rear_wheel_drive,2.0,luxury,compact,convertible,28,18,3916,34500